In [18]:
# Import the Pandas library
import pandas as pd

In [19]:
# Create a reference the CSV file desired
csv = pd.read_csv('../secondday/ufo.csv')

# Read the CSV into a Pandas DataFrame
ufo = pd.DataFrame(csv)
# Print the first five rows of data to the screen
ufo.head()

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700.0,45 minutes,This event took place in early fall around 194...,4/27/2004,29.883056,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200.0,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.384210,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20.0,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.200000,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20.0,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.978333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.418056,-157.803611

In [20]:
# Check to see if there are any rows with missing data
ufo.count()

datetime                6123
city                    6123
state                   5799
country                 5464
shape                   6007
duration (seconds)      6123
duration (hours/min)    6123
comments                6122
date posted             6122
latitude                6122
longitude               6122
dtype: int64

In [21]:
# Remove the rows with missing data
df = ufo.dropna(how='any')
df.count()

datetime                5225
city                    5225
state                   5225
country                 5225
shape                   5225
duration (seconds)      5225
duration (hours/min)    5225
comments                5225
date posted             5225
latitude                5225
longitude               5225
dtype: int64

In [22]:
# Filter the data so that only those sightings in the US are in a DataFrame
df.loc[df['country'] == 'us',:]

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700.0,45 minutes,This event took place in early fall around 194...,4/27/2004,29.883056,-97.941111
3,10/10/1956 21:00,edna,tx,us,circle,20.0,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.978333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.418056,-157.803611
5,10/10/1961 19:00,bristol,tn,us,sphere,300.0,5 minutes,My father is now 89 my brother 52 the girl wit...,4/27/2007,36.595000,-82.188889
7,10/10/1965 23:45,norwalk,ct,us,disk,1200.0,20 minutes,A bright orange color changing to reddish colo...,10/2/1999,41.117500,-73.408333
8,10/10/1966 20:00,pell city,al,us,disk,180.0,3 minutes,Strobe Lighted disk shape object observed clos...,3/19/2009,33.586111,-86.286111
9,10/10/1966 21:00,live oak,fl,us,disk,120.0,several minutes,Saucer zaps energy from powerline as my pregna...,5/11/2005,30.294722,-82.984167
10,10/10/1968 13:00,hawthorne,ca,us,circle,300.0,5 min.,ROUND &#44 ORANGE &#44 WITH WHAT I WOULD SAY W...,10/31/2003,33.916389,-118.351667
11,10/10/1968 19:00,brevard,nc,us,fireball,180.0,3 minutes,silent red /orange mass of energy floated by t...,6/12/2008,35.233333,-82.734444
12,10/10/1970 16:00,bellmore,ny,us,disk,1800.0,30 min.,silver disc seen by family and neighbors,5/11/2000,40.668611,-73.527500
13,10/10/1970 19:00,manchester,ky,us,unknown,180.0,3 minutes,Slow moving&#44 silent craft accelerated at an...,2/14/2008,37.153611,-83.761944
14,10/10/1971 21:00,lexington,nc,us,oval,30.0,30 seconds,green oval shaped light over my local church&#...,2/14/2010,35.823889,-80.253611
15,10/10/1972 19:00,harlan county,ky,us,circle,1200.0,20minutes,On october 10&#44 1972 myself&#44my 5yrs.daugh...,9/15/2005,36.843056,-83.321944
16,10/10/1972 22:30,west bloomfield,mi,us,disk,120.0,2 minutes,The UFO was so close&#44 my battery in the car...,8/14/2007,42.537778,-83.233056
17,10/10/1973 19:00,niantic,ct,us,disk,1800.0,20-30 min,Oh&#44 what a night &#33 Two (2) saucer-shape...,9/24/2003,41.325278,-72.193611
19,10/10/1974 19:30,hudson,ma,us,other,2700.0,45 minutes,Not sure of the eact month or year of this sig...,8/10/1999,42.391667,-71.566667
21,10/10/1974 23:00,hudson,ks,us,light,1200.0,one hour?,The light chased us.,7/25/2004,38.105556,-98.659722
22,10/10/1975 17:00,north charleston,sc,us,light,360.0,5-6 minutes,Several Flashing UFO lights over Charleston Na...,2/14/2008,32.854444,-79.975000
23,10/10/1976 20:30,washougal,wa,us,oval,60.0,1 minute,Three extremely large lights hanging above nea...,2/7/2014,45.582778,-122.352222
25,10/10/1977 12:00,san antonio,tx,us,other,30.0,30 seconds,i was about six or seven and my family and me ...,2/24/2005,29.423889,-98.493333
26,10/10/1977 22:00,louisville,ky,us,light,30.0,approx: 30 seconds,HBCCUFO CANADIAN REPORT: Pilot Sighting Of Un...,3/17/2004,38.254167,-85.759444
27,10/10/1978 2:00,elmont,ny,us,rectangle,300.0,5min,A memory I will never forget that happened men...,2/1/2007,40.700833,-73.713333
28,10/10/1979 0:00,poughkeepsie,ny,us,chevron,900.0,15 minutes,1/4 moon-like&#44 its &#39chord&#39 or flat s...,4/16/2005,41.700278,-73.921389
30,10/10/1979 22:00,san diego,ca,us,oval,180.0,3 minutes,My 2nd UFO sighting&#44 October 1979,8/5/2001,32.715278,-117.156389
31,10/10/1979 22:00,security,co,us,unknown,1800.0,30mins.,very low clouds all different colors&#44search...,1/28/1999,38.758333,-104.742500
32,10/10/1980 19:00,houston,tx,us,sphere,180.0,3 min,Sphere&#44 No lights&#44 moving through neigh...,4/16/2005,29.763056,-95.363056
33,10/10/1980 22:00,dallas,tx,us,unknown,300.0,5 minutes,Strange shape shifting craft of pure light ene...,10/28/2002,32.783333,-96.800000
34,10/10/1980 23:30,manchester,nh,us,light,300.0,3 to 5 min,A red glowing sphere stopped and watched me.,11/21/2010,42.995556,-71.455278
36,10/10/1984 5:00,houston,tx,us,circle,60.0,1 minute,2 experience with unkown,4/18/2012,29.763056,-95.363056
37,10/10/1984 12:00,traverse city,mi,us,other,120.0,couple minutes,translucent football seen over city airport,10/7/2003,44.763056,-85.620556
...,...,...,...,...,...,...,...,...,...,...,...
6088,10/3/2004 19:00,tullahoma,tn,us,changing,3600.0,1 hour,UFO sighted in the Tullahoma TN vicinity...,10/27/2004,35.361944,-86.209444
6089,10/3/2004 19:05,cleveland,oh,us,circle,30.0,30sec.,Many fighter jets flying towards UFO,10/27/2004,41.499444,-81.695556
6091,10/3/2004 20:10,porter ranch,ca,us,light,60.0,1 minute,Extremely bright yellow-orange light zipping a...,10/27/2004,34.275150,-118.549800
6092,10/3/2004 20:30,martinsburg,wv,us,light,7200.0,2 hours,Five objects that moved too slowly to be any a...,10/27/2004,39.456111,-77.964167
6094,10/3/2005 11:00,san jose,ca,us,formation,180.0,3 min,It was 11:00 am&#44 my daughter 4 1/2 was our ...,10/11/2005,37.339444,-121.893889
6095,10/3/2005 12:00,westfir,or,us,other,1200.0,20 minutes,clear real photo graph of extraterestrel,10/11/2005,43.757500,-122.495278
6096,10/3/2005 21:00,whitefield,nh,us,light,14400.0,4 hours,((NUFORC Note: Probably a twinkling star. PD...,10/11/2005,44.373056,-71.610556
6097,10/3/2005 21:30,boulder,co,us,chevron,45.0,45 seconds,Low flying&#44 silent&#44 muted white lights o...,10/11/2005,40.015000,-105.270000
6098,10/3/2005 21:40,castle rock,co,us,oval,3600.0,1hr,On Monday october 3&#44 2005&#44 I spotted two...,10/11/2005,39.372222,-104.855556
6100,10/3/2005 22:30,burlington,vt,us,disk,900.0,15 minutes,2 low flying brightly lit and quiet objects in...,10/20/2005,44.475833,-73.212500
6101,10/3/2005 23:00,ogden,ut,us,circle,300.0,5 min,October 3rd 11:40pm 05 above the eastern bench...,10/11/2005,41.223056,-111.973056
6102,10/3/2005 23:18,cherry hill,nj,us,circle,120.0,2mins,Three white objects in triangle formation hove...,10/11/2005,39.934722,-75.031111
6103,10/3/2006 0:15,newburgh,in,us,sphere,120.0,2 minutes,Large orange ball of light hovering 200-300 fe...,10/30/2006,37.944444,-87.405278
6104,10/3/2006 3:30,braintree,ma,us,light,2700.0,45 minutes,We witnessed blinking lights that moved rapidl...,10/30/2006,42.222222,-71.000000
6105,10/3/2006 3:30,milwaukee,wi,us,sphere,3600.0,1 hour,Reaccuring semi-stationary&#44 color alternati...,10/30/2006,43.038889,-87.906389
6106,10/3/2006 3:40,utica,ny,us,cigar,600.0,10 min,I was looking at the stars&#44as I stopped on ...,10/30/2006,43.100833,-75.233056
6107,10/3/2006 17:25,oceanside,ca,us,unknown,120.0,1 or 2 minutes,Silver metallic object seen hovering high abov...,10/30/2006,33.195833,-117.378611
6108,10/3/2006 19:00,bailey,co,us,sphere,900.0,10-15 minutes,Colorado 10/03/06,10/30/2006,39.405556,-105.472778
6109,10/3/2006 19:30,shreveport,la,us,unknown,480.0,6-8 minutes,2 different objects seen in Louisiana,10/30/2006,32.525000,-93.750000
6110,10/3/2006 20:00,miles city,mt,us,oval,600.0,10min&#44 to 15&#44 min,was sitting at my porch watching the evening s...,12/7/2006,46.408333,-105.840000
6111,10/3/2006 20:15,garfield,ar,us,unknown,45.0,about 45 sec.,2 LIIGHTS OVER BEAVER LAKE.,10/30/2006,36.448333,-93.973889
6112,10/3/2006 21:00,canton,ga,us,unknown,2.0,a few seconds at a time f,Black spec passing in front of the moon severa...,10/30/2006,34.236667,-84.490833
6113,10/3/2006 21:00,dufur,or,us,disk,120.0,2 minutes,3 flashing lights at exact distances crossed e...,10/30/2006,45.453333,-121.129444
6114,10/3/2006 21:43,ravenna,oh,us,other,30.0,30 seconds,Shooting Object Across Ravenna Sky,10/30/2006,41.157500,-81.242222
6116,10/3/2006 22:00,lakewood,ca,us,fireball,240.0,4min,Dripping ball of light,10/30/2006,33.853611,-118.133056
6117,10/3/2006 23:15,santa fe,nm,us,cone,60.0,approx 1 minute,Fiery object moving south to north which separ...,10/30/2006,35.686944,-105.937222
6118,10/3/2006 23:25,orange,ca,us,other,600.0,10 minutes,Oddly shaped object hovering above Orange Coun...,10/30/2006,33.787778,-117.852222
6119,10/3/2006 23:45,portland,or,us,circle,2700.0,45 minutes,Two nights after my first encounter I spotted ...,10/30/2006,45.523611,-122.675000
6120,10/3/2007 0:00,high point,nc,us,triangle,900.0,15 mins,bright lights spinning in the sky,10/8/2007,35.955556,-80.005556
6121,10/3/2007 0:00,high springs,fl,us,triangle,300.0,2-5 minutes,Object aproxamitly 200ft high and moving slowl...,3/4/2008,29.826667,-82.596944

In [28]:
# Count how many sightings have occured within each state
sm = df['state'].value_counts()

In [29]:
# Convert the state_counts Series into a DataFrame
df = pd.DataFrame(sm)

In [30]:
# Convert the column name into "Sum of Sightings"
df.rename(columns={'state':'Sum of Sightings'}).head()

    Sum of Sightings
ca               596
tx               337
wa               273
fl               270
ny               234

In [31]:
# Want to add up the seconds UFOs are seen? There is a problem
df.sum()

# Problem can be seen by examining datatypes within the DataFrame

state    5225
dtype: int64